version: "3.1"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: strapi4-knex-issue-demonstration
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
